name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydatabase

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser -d mydatabase"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose


      - name: Start application services
        run: |
          docker-compose up -d
          sleep 20  # Give services time to start

      - name: Run API tests
        run: |
          pytest tests/

      - name: Stop services
        run: |
          docker-compose down

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR  
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker images to GHCR
        run: |
          docker-compose build
          docker tag user_api ghcr.io/${{ github.repository }}/user_api:latest
          docker tag user_interface ghcr.io/${{ github.repository }}/user_interface:latest
          docker tag admin_api ghcr.io/${{ github.repository }}/admin_api:latest
          docker tag admin_interface ghcr.io/${{ github.repository }}/admin_interface:latest
          docker push ghcr.io/${{ github.repository }}/user_api:latest
          docker push ghcr.io/${{ github.repository }}/user_interface:latest
          docker push ghcr.io/${{ github.repository }}/admin_api:latest
          docker push ghcr.io/${{ github.repository }}/admin_interface:latest
